### ISSUE TITLE
Is there any reason why this library build on top of BigInt?

### ISSUE THREAD

**Issue by nanlei2000** [Yaffle/BigDecimal#2]
I saw that you implement two version of the decimal proposal , one is on top of BIgInt, and another use the `decimal.js`,
what is the advantage and disadvantage between this two way?

**Comment by Yaffle** [comment]
The second is a ready to use decimal library, i am using it to test against my implementation, test.js has some random tests

**Comment by nanlei2000** [comment]
I don't konw how the decimal.js being implemented，i think the way that build on top of BigInt will benifit the 
native performance，am i correct?

**Comment by nanlei2000** [comment]
And i found there is no way transform this library to jsbi, cause that babel plugin can only transform jsbi to native BigInt(not reverse).

**Comment by Yaffle** [comment]
> I don't konw how the decimal.js being implemented, i think the way that build on top of BigInt will benifit the
> native performance, am i correct?

Yes, perhaps, and this is also some separation of code...

**Comment by Yaffle** [comment]
> And i found there is no way transform this library to jsbi, cause that babel plugin can only transform jsbi to native BigInt(not reverse).

The plugin in readme transforns code to use JSBI

**Comment by nanlei2000** [comment]
In fact, i want to implement a 

> > And i found there is no way transform this library to jsbi, cause that babel plugin can only transform jsbi to native BigInt(not reverse).
> 
> The plugin in readme transforms code to use JSBI

Sorry, i am wrong, you made a reverse transformer, that's awesome! In fact, i want made a similar library too, to deal with both decimal and bigint, is anything i can help with the code?

**Comment by Yaffle** [comment]
The babel plugin is a little buggy right now and needs to be fixed.
You could try to implement some fast decimal library or update the code of this library :-)
Some benchmark is needed to compare libs.
In this library many things are not perfect like binary to decimal conversion or math functions, not sure as well how to efficiently implement rounding.
Someone also mentions another library - https://github.com/tc39/proposal-decimal/issues/27#issuecomment-743455396 - with a benchmark results...
Btw, I prefer to use BigFloat, as in this case it is possible to use bitwise shifts, which are faster.
