### ISSUE TITLE
Print and read back

### ISSUE THREAD

**Issue by munrocket** [Yaffle/BigDecimal#6]
It looks like some of the methods not implemented for Base10/Base2 this lead to problem that it is impossible to print and read back BigFloat/BigDecimal.

* BF.toString() - not exist, you should use .toExponential().
* BF.BF(`string in expoinential form`) - gives an error.

Maybe I miss something? Should I use .toFixed() and remove trailing zeros?

**Comment by Yaffle** [comment]
The problem is that 0.1 cannot be represented in the used binary structure.
And the spec proposal has no details how to do this. Perhaps, BigFloat.round should accept decimal string and rounding should be applied.
I have decided to skip it so.

**Comment by munrocket** [comment]
Looks like I should switch to BigDecimal because BigFloat constructors is not flexible enough.

**Comment by munrocket** [comment]
What was your reference for implementing this?
I want the same for glsl with two uint32. It seems this implementation can be faster than [SoftFloat](http://www.jhauser.us/arithmetic/SoftFloat.html)

**Comment by Yaffle** [comment]
May be, BigFloat should be separated into another small libraries where no transendent math is needed and no string conversion methods, as today my implementations arenot perfect.
For BigDecimal they can be simplified a lot as base convertion is not needed

**Comment by munrocket** [comment]
Yea, can be a good idea, but string conversions always needed in any application.
I like the implementation but API can be easier like in wasm/big.js. Right now I am using it with wrapper because of that.

**Comment by munrocket** [comment]
I think you can add it in https://github.com/josdejong/mathjs after that.
